### PR TITLE
improve things

### PR DESCRIPTION
**Pull request by pacak**
- new version is about 15 times faster for 12 character sized ISINs
- allocations are gone, in theory luhn-rs can now process VERY big inputs
- tests are less repeating

I basically replaced everything...

### CODE REVIEW

**Comment by pacak** [comment]
Noticed some minor issues, closing for now

**Comment by pacak** [comment]
Actually the problem is not in the updated code but in code that uses it...

**Comment by pacak** [comment]
Added a bunch more tests, found an off by one error. Will push something soon.

**Comment by jeffcarp** [comment]
Hey sorry for the delay! Thanks for this, I don't have a ton of time to review right now but if you reopen I'll get to it soon.

**Pull request closed without merging**
